version: '3.1'
services:
  app:
    container_name: spring-boot-container
    image: spring-boot-image
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=nhatcuong123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=authorization