version : "2.1"
services:
  eureka:
    image: microservice/server
    container_name: eureka
    hostname: eureka
    ports:
      - "8761:8761"
    networks:
      - microservicesnet

  zuul:
    image: microservice/zuul
    container_name: zuul
    ports:
     - "8762:8762"
    networks:
      - microservicesnet

  team:
    image: microservice/team
    container_name: team
    ports:
       - "8201:8201"
    networks:
      - microservicesnet
 
  member:
    image: microservice/member
    container_name: member
    ports:
       - "8202:8202"
    networks:
      - microservicesnet

networks:
  microservicesnet: